modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/MysticMods/Druidcraft/issues"
license="GNU Lesser General Public License"

[[mods]]
modId="druidcraft"
version="0.4.46"
mcversion= "1.16.1"
displayName="Druidcraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/druidcraft"
credits="Java, Forge, MCP, Minecraft, and the Mystic team for supporting me!"
authors="VulpTheHorseDog"
description='''
A druid-focused splice-of-life mod that's currently in very early stages.

Regardless, I hope you enjoy the features as they're rolled out! :)
'''

[[dependencies.druidcraft]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.108,)"
    ordering="NONE"
    side="BOTH"